### ISSUE TITLE
math_ops_speed comparison

### ISSUE THREAD

**Issue by axelpale** [elgw/math_ops_speed#1]
Thank you for the great benchmark. I wanted to let you know I borrowed some ideas from this when I designed a [similar benchmark](https://github.com/axelpale/js-math-ops-speed) for JavaScript/Node.js. Also, I compared your results to [Lincoln Atkinson's](https://latkin.org/blog/2014/11/09/a-simple-benchmark-of-various-math-operations/) and mine in a related article [Benchmark of Elementary Mathematical Operations in Node.js](https://www.akselipalen.com/2021/01/13/benchmark-of-elementary-mathematical-operations-in-node-js/). The results were roughly similar which is good as it brings confidence to the interpretation of the results.

I was wondering if you were interested in expanding math_ops_speed readme with a link to the comparative article? No pressure, I totally understand if you would like to keep the readme minimal. I am just happy that these kind of benchmarks exist. Cheers!

**Comment by elgw** [comment]
Thanks for putting the three of them on the same page! Your links are added to the readme :)
Cheers! / Erik
